import os
import qrcode
from datetime import datetime
from qrcode.constants import ERROR_CORRECT_H


def generate_qr(data: str,
                filename: str = None,
                folder: str = ".",
                box_size: int = 10,
                border: int = 4,
                error_correction=ERROR_CORRECT_H,
                image_format: str = "PNG") -> str:
    """
    Generate a 2D QR code image from `data`, save it, and return the saved file path.

    Parameters:
      - data: text to encode (required)
      - filename: optional filename (if None, autogenerated with timestamp)
      - folder: folder to save into (defaults to current directory)
      - box_size: pixel size of each QR box (increase for larger QR)
      - border: border boxes around QR (standard is 4)
      - error_correction: one of qrcode.constants.ERROR_CORRECT_{L,M,Q,H}
      - image_format: "PNG", "JPEG", or "SVG" (SVG requires different image factory)

    Returns:
      - full path to the saved image file (string)
    """

    if not isinstance(data, str) or data == "":
        raise ValueError("`data` must be a non-empty string.")

    os.makedirs(folder, exist_ok=True)

    if filename is None:
        ts = datetime.utcnow().strftime("%Y%m%dT%H%M%S%f")[:-3]
        filename = f"qr_{ts}.{image_format.lower()}"

    if image_format.upper() in ("PNG", "JPG", "JPEG"):
        qr = qrcode.QRCode(
            version=None,
            error_correction=error_correction,
            box_size=box_size,
            border=border,
        )
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        path = os.path.join(folder, filename)
        img.save(path, format=image_format.upper())
        return os.path.abspath(path)



if __name__ == "__main__":
    # Testing
    path = generate_qr("9054413199", folder="qrs")
    print("Saved:", path)
